language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
before_install:
  - export PIP_USE_MIRRORS=true
  - export PIP_INDEX_URL=https://simple.crate.io/
install:
  - pip install -e .
  - pip install -r requirements/tests.txt Django==$DJANGO
before_script:
  - flake8 dbtemplates --ignore=E501
script:
  - django-admin.py test --settings=django_hosts.test_settings django_hosts
env:
  - DJANGO=1.2.7
  - DJANGO=1.3.1
  - DJANGO=1.4
branches:
  only:
    - develop
