sudo: no
language: python
install:
  - pip install tox coveralls
script:
  - tox
env:
  - TOXENV=py26-django-16
  - TOXENV=py27-django-16
  - TOXENV=py27-django-17
  - TOXENV=py32-django-16
  - TOXENV=py32-django-17
  - TOXENV=py33-django-16
  - TOXENV=py33-django-17
  - TOXENV=py34-django-16
  - TOXENV=py34-django-17
after_success: coveralls
