language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - export PIP_USE_MIRRORS=true
  - export PIP_INDEX_URL=https://simple.crate.io/
install:
  - pip install -e .
  - pip install -r requirements/tests.txt
  - pip install https://github.com/django/django/archive/${DJANGO}.zip#egg=django
script: make test
env:
  - DJANGO=1.4.5
  - DJANGO=1.5.1
  - DJANGO=master
